name: NewChatHook
version: 0.0.1
author: archessmn
main: com.github.archessmn.NewChatHook.Main
api-version: 1.16

commands:
  link:
    description: Used for linking your Discord account to your Minecraft account.